name: publish

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - LICENSE
      - SECURITY.md
      - '.github/**'
      - Makefile
      - contributing.md
      - .gitignore
      - working-group-charter.md
      
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - LICENSE
      - SECURITY.md
      - '.github/**'
      - Makefile
      - contributing.md
      - .gitignore
      - working-group-charter.md
  workflow_dispatch:

jobs:
  build-sharedsignals:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install kramdown-rfc
        run: gem install kramdown-rfc
      - name: Install xml2rfc
        run: pip install xml2rfc
      - name: Convert sharedsignals md to xml
        run: kramdown-rfc2629 1.0/openid-sharedsignals-framework-1_0.md > 1.0/openid-sharedsignals-framework-1_0.xml
      - name: Render HTML
        run: xml2rfc 1.0/openid-sharedsignals-framework-1_0.xml --html -o 1.0/openid-sharedsignals-framework-1_0.html
      - name: Render Text
        run: xml2rfc 1.0/openid-sharedsignals-framework-1_0.xml --text
      - name: Render risc html
        run: xml2rfc 1.0/openid-risc-1_0.xml --html -o 1.0/openid-risc-1_0.html
      - name: Render risc text
        run: xml2rfc 1.0/openid-risc-1_0.xml --text -o 1.0/openid-risc-1_0.txt
      - name: Convert caep md to xml
        run: kramdown-rfc2629 1.0/openid-caep-1_0.md > 1.0/openid-caep-1_0.xml
      - name: Render caep html
        run: xml2rfc 1.0/openid-caep-1_0.xml --html -o 1.0/openid-caep-1_0.html
      - name: Render caep text
        run: xml2rfc 1.0/openid-caep-1_0.xml --text -o 1.0/openid-caep-1_0.txt
      - name: Convert sharedsignals 1.1 md to xml
        run: kramdown-rfc2629 1.1/openid-sharedsignals-framework-1_1.md > 1.1/openid-sharedsignals-framework-1_1.xml
      - name: Render 1.1 HTML
        run: xml2rfc 1.1/openid-sharedsignals-framework-1_1.xml --html -o 1.1/openid-sharedsignals-framework-1_1.html
      - name: Render 1.1 Text
        run: xml2rfc 1.1/openid-sharedsignals-framework-1_1.xml --text -o 1.1/openid-sharedsignals-framework-1_1.txt
      - name: Render risc 1.1 html
        run: xml2rfc 1.1/openid-risc-1_1.xml --html -o 1.1/openid-risc-1_1.html
      - name: Render risc 1.1 text
        run: xml2rfc 1.1/openid-risc-1_1.xml --text -o 1.1/openid-risc-1_1.txt
      - name: Convert caep 1.1 md to xml
        run: kramdown-rfc2629 1.1/openid-caep-1_1.md > 1.1/openid-caep-1_1.xml
      - name: Render caep 1.1 html
        run: xml2rfc 1.1/openid-caep-1_1.xml --html -o 1.1/openid-caep-1_1.html
      - name: Render caep 1.1 text
        run: xml2rfc 1.1/openid-caep-1_1.xml --text -o 1.1/openid-caep-1_1.txt
      - name: Convert caep-interop md to xml
        run: kramdown-rfc2629 openid-caep-interoperability-profile-1_0.md > openid-caep-interoperability-profile-1_0.xml
      - name: Render caep-interop html
        run: xml2rfc openid-caep-interoperability-profile-1_0.xml --html -o openid-caep-interoperability-profile-1_0.html
      - name: Render caep-interop text
        run: xml2rfc openid-caep-interoperability-profile-1_0.xml --text -o openid-caep-interoperability-profile-1_0.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: specfiles
          path: |
            1.0/openid-sharedsignals-framework-1_0.html
            1.0/openid-sharedsignals-framework-1_0.txt
            1.0/openid-risc-1_0.html
            1.0/openid-risc-1_0.txt
            1.0/openid-caep-1_0.html
            1.0/openid-caep-1_0.txt
            1.1/openid-sharedsignals-framework-1_1.html
            1.1/openid-sharedsignals-framework-1_1.txt
            1.1/openid-risc-1_1.html
            1.1/openid-risc-1_1.txt
            1.1/openid-caep-1_1.html
            1.1/openid-caep-1_1.txt
            openid-caep-interoperability-profile-1_0.html
            openid-caep-interoperability-profile-1_0.txt
  publish-to-pages:
    if: github.ref == 'refs/heads/main'
    needs: [build-sharedsignals]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: specfiles
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
